name: "pull-request-auto-reviewer"
description: "auto post comments based on changes"
branding:
  icon: "message-square"
  color: "yellow"
inputs:
  token:
    description: "token for github"
  datapath:
    description: "path to data yaml file"
runs:
  using: "node20"
  main: "dist/index.js"
