name: "Hello World"
description: "Greet someone and record the time"
inputs:
  token:
    description: "token for github"
  datapath:
    description: "path to data yaml file"
runs:
  using: "node20"
  main: "dist/index.min.js"
