on:
  pull_request:
    branches:
      - main

jobs:
  comment:
    name: job to post comment(s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check component dependencies
        uses: ./
        id: components-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          datapath: docs/data.yml
