on:
  pull_request:
    branches:
      - main

jobs:
  review:
    name: post comment(s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: analyse changes
        uses: ./
        id: auto-review-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          datapath: docs/data.yml
